version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: calendator
      POSTGRES_USER: calendatorUser
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
